### ISSUE TITLE
[Google Trends API] No Data Prior to 2018 on Some Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#785] opened 2023-04-12 16:49 UTC
A user reported some of their Google Trends searches are missing data for some dates. They shared an example where all data from 2017 and before is missing. I was unable to replicate it in the Playground.

![missing_google_trends_2017](https://user-images.githubusercontent.com/30915304/231526659-048d7c44-d0e5-4ffb-9a0c-1932225c0b9e.png)

[Search Inspector](https://serpapi.com/searches/6436dd698b7ed24045ede5fe/inspect) | [Playground (couldn't replicate) ](https://serpapi.com/playground?engine=google_trends&q=Automobile&data_type=TIMESERIES&date=2012-01-01+2023-03-31)

**Comment by ilyazub** [comment] 2023-04-14 12:45
Duplicate of https://github.com/serpapi/public-roadmap/issues/561.

**Closed** 2023-04-14 12:45 UTC
