### ISSUE TITLE
[Google Search API] `organic_results` with `carousel` videos not parsed

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#465] opened 2022-11-03 10:31 UTC
![pew](https://user-images.githubusercontent.com/73674035/199698775-3e704adf-895a-4b6b-867f-b1aa2a825e34.png)

[Inspect](https://serpapi.com/searches/636397a894fb0369c0c2844b/inspect)
[Playground](https://serpapi.com/playground?q=Pewdiepie&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client)

Don't know if it could be resolved with https://github.com/serpapi/public-roadmap/issues/453 (unlikely though)

**Comment by ilyazub** [comment] 2022-11-16 21:45
Duplicate of https://github.com/serpapi/public-roadmap/issues/87

**Closed by ilyazub** 2022-11-16 21:45 UTC
Labels: next
