### ISSUE TITLE
[Google Search API] Not working correctly fetching results from 2nd and more page of Google Images Results

### ISSUE THREAD

**Issue by Anatolian-grav** [serpapi/public-roadmap#471] opened 2022-11-06 13:21 UTC
I try to make a simple request from your playground, for example: 

- https://serpapi.com/playground?q=Apple&gl=us&hl=en&tbm=isch&ijn=1&device=desktop&newPara=tbs

The page is not showing correctly (in built-in html viewer widget on playground), but json response seems to be correct.
But if i make ijn=2 or greatest, it will be mistake (in json) `"error": "Google hasn't returned any results for this query."` . 

It is strange, because google have many photos from this query. If i make this actions trough python api, i get the same response.

Full response in json (from playground):

```json
{
   "search_metadata":{
      "id":"6367b3529bddf75282c8f590",
      "status":"Success",
      "json_endpoint":"https://serpapi.com/searches/07c877eaab70635d/6367b3529bddf75282c8f590.json",
      "created_at":"2022-11-06 13:14:58 UTC",
      "processed_at":"2022-11-06 13:14:58 UTC",
      "google_url":"https://www.google.com/search?q=Apple&oq=Apple&hl=en&gl=us&tbm=isch&ijn=2&asearch=ichunk&async=_id:rg_s,_pms:s,_fmt:pc&sourceid=chrome&ie=UTF-8",
      "raw_html_file":"https://serpapi.com/searches/07c877eaab70635d/6367b3529bddf75282c8f590.html",
      "total_time_taken":4.65
   },
   "search_parameters":{
      "engine":"google",
      "q":"Apple",
      "google_domain":"google.com",
      "hl":"en",
      "gl":"us",
      "ijn":"2",
      "device":"desktop",
      "tbm":"isch"
   },
   "search_information":{
      "image_results_state":"Fully empty"
   },
   "error":"Google hasn't returned any results for this query."
}
```

**Comment by dimitryzub** [comment] 2022-11-07 06:51
Hey, @Anatolian-grav 🙂Thank you for opening this issue. 

I can confirm that there's a problem (with no `gl`, `hl` params also, and different Google domains):

![image](https://user-images.githubusercontent.com/78694043/200242736-cf17f4e9-1f1e-4370-90c7-247fd0d85278.png)

It seems like we need to make adjustments to our parser. It will take a few days to a week+ depending on the complexity of a problem.

We'll update you once the issue is fixed. Labeling it as a `next` to focus on.

Sorry for such inconvenience 🐱

**Comment by tanys123** [comment] 2022-11-07 08:41
Thanks @Anatolian-grav  for reporting the issue. I have tried it from [Google](https://www.google.com/search?q=Apple&oq=Apple&tbm=isch&sourceid=chrome&ie=UTF-8) directly and for `Apple` query it does end on 2nd page. You can test out another query `Coffee` which generate much more results. Please let me know if you have more questions. Thanks 👍

**Comment by ilyazub** [comment] 2024-05-15 14:34
Closing this issue because Google Images return only two pages for the `Apple` query, but more pages for other search queries like `Coffee`.

![image](https://github.com/serpapi/public-roadmap/assets/282605/27176617-fb21-4d65-a6d3-3f9b602cf558)
(ref: https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&ijn=3&device=desktop)

**Closed by ilyazub** 2024-05-15 14:34 UTC
Labels: status: queued
