### ISSUE TITLE
[Google Search API] Unsupported `hl=en-US` interface language

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#779] opened 2023-04-10 09:26 UTC
This is the `kgmid` [serpapi link ](https://serpapi.com/search.json?device=desktop&engine=google&gl=us&google_domain=google.com&hl=en-US&kgmid=%2Fm%2F02vqfm&location=Austin%2C+Texas%2C+United+States&q=Coffee)from this search: 
[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%252C+Texas%252C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com]
) |  [Inspect](https://serpapi.com/searches/6433d50c116a5523aa553998/inspect)

<img width="913" alt="image" src="https://user-images.githubusercontent.com/99160364/230874338-6cbfa230-3616-4b25-b123-5740a560fba5.png">

It returns an error: `"Unsupported `en-US` interface language - hl parameter."`

**Comment by ilyazub** [comment] 2024-05-15 15:21
Closing as a duplicate of https://github.com/serpapi/public-roadmap/issues/1553 (will be fixed in serpapi/SerpApi/pull/4756).

**Closed by ilyazub** 2024-05-15 15:21 UTC
Labels: status: queued, type: bug
