### ISSUE TITLE
[Google Maps API] Results from Unrelated Places Appear

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#86] opened 2022-03-23 10:02 UTC
One of our users scrape gas stations in Panama and after the first page, gas stations from the USA is returned in JSON results.

[The Playground](https://serpapi.com/playground?engine=google_maps&q=Gas+station&ll=%408.39946%2C-80.261043%2C15z&google_domain=google.com.pa&hl=es&type=search&start=20) | [The Inspect](https://serpapi.com/searches/623aee082ff421e896bab300/inspect)
<img width="959" alt="mapsgasstations" src="https://user-images.githubusercontent.com/64849049/159673748-a6c0e8e0-7d41-4644-a4fb-48832fcab356.PNG">

**Comment by ilyazub** [comment] 2022-03-29 08:53
It seems to be related to [Google Maps incorrectly scraping results with correct `ll` parameter](https://forum.serpapi.com/bugs/p/google-maps-incorrectly-scraping-results-with-correct-ll-parameter) that was fixed a few months ago.

**Comment by zyc9012** [comment] 2024-01-10 13:43
Closing as unable to reproduce.

**Closed by zyc9012** 2024-01-10 13:43 UTC
Labels: status: queued
