### ISSUE TITLE
[Google Search API] Num=100 Parameter Not Working in Germany Domain with Certain Search Terms

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#235] opened 2022-07-21 14:19 UTC
It seems that num=100 does not seem to be working on google.de domain, **only with certain query term which is "swinemünde".** It return 10 results despite num=100.

Interestingly, when I search for the same term on my mobile and add num=100, it returns 100 results.

[The Playground](https://serpapi.com/playground?q=swinem%C3%BCnde&location=10117%2C+Berlin%2C+Germany&google_domain=google.de&gl=de&hl=de&num=100&device=mobile&no_cache=true) | [The Inspect](https://serpapi.com/searches/62d95c9410d7446045014407/inspect)

```
"search_parameters":
{

    "engine": "google",
    "q": "swinemünde",
    "location_requested": "10117, Berlin, Germany",
    "location_used": "10117,Berlin,Germany",
    "google_domain": "google.de",
    "hl": "de",
    "gl": "de",
    "num": "100",
    "device": "mobile"
```

```
     {
        "position": 10,
        "title": "Swinemünde - Im Land der 44 Inseln - Usedom Insider",
        "link": "https://www.usedom-insider.de/swinemuende-2/",
        "displayed_link": "https://www.usedom-insider.de › swi...",
        "snippet": "Auf der Insel Usedom findest Du im östlichen Teil, gleich neben Ahlbeck gelegen, die polnische Hafenstadt Swinemünde, die zur “Woiwodschaft” Westpommerns ..."
    }

]
,
"pagination":
{

    "current": 1,
    "next": "https://www.google.de/search?q=swinem%C3%BCnde&oq=swinem%C3%BCnde&hl=de&gl=de&num=100&start=100&sourceid=chrome-mobile&ie=UTF-8",
    "other_pages":
    {
        "https://www.google.de/search?q=swinem%C3%BCnde&oq=swinem%C3%BCnde&hl=de&gl=de&num=100&start=100&sourceid=chrome-mobile&ie=UTF-8",
        "https://www.google.de/search?q=swinem%C3%BCnde&oq=swinem%C3%BCnde&hl=de&gl=de&num=100&start=200&sourceid=chrome-mobile&ie=UTF-8",
        "https://www.google.de/search?q=swinem%C3%BCnde&oq=swinem%C3%BCnde&hl=de&gl=de&num=100&start=300&sourceid=chrome-mobile&ie=UTF-8",
        "https://www.google.de/search?q=swinem%C3%BCnde&oq=swinem%C3%BCnde&hl=de&gl=de&num=100&start=400&sourceid=chrome-mobile&ie=UTF-8"
    }

}
```

**Other search terms** with exactly the same parameters returns 100 results.

[The Playground](https://serpapi.com/playground?q=klarna&location=10117%2C+Berlin%2C+Germany&google_domain=google.de&gl=de&hl=de&num=100&device=mobile&no_cache=true) | [The Inspect](https://serpapi.com/searches/62d95d20defa13d5d6701315/inspect)

**Comment by ilyazub** [comment] 2024-05-15 14:29
Duplicate of https://github.com/serpapi/public-roadmap/issues/753.

As a workaround, please try our [Google Light Search API](https://serpapi.com/google-light-api).

![image](https://github.com/serpapi/public-roadmap/assets/282605/d2b97077-226d-4f9f-93fb-ab9c98a10c81)
(ref: https://serpapi.com/search?q=swinem%C3%BCnde&location=10117%2C+Berlin%2C+Germany&google_domain=google.de&gl=de&hl=de&num=100&device=mobile&engine=google_light)

**Closed by ilyazub** 2024-05-15 14:29 UTC
Labels: status: queued
