### ISSUE TITLE
[Google Search API] Mistakenly parsed `phone` for some `ads`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1028] opened 2023-08-08 12:52 UTC
<img width="1458" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/61daaaba-00b5-4d84-a636-5fba0605cb9f">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=50&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client)
[Inspect](https://serpapi.com/searches/64d2276b9c84acd8395a59ea/inspect)

**Comment by aciddjus** [comment] 2024-05-30 13:57
Closing the issue as I can't reproduce it.

**Closed by aciddjus** 2024-05-30 13:57 UTC
Labels: status: freezer
