### ISSUE TITLE
[Sports Results] Matches Not Scraped

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1352] opened 2024-01-12 21:44 UTC
A user reported that for Sports Results where "Matches" appear in the HTML, we are not parsing them.

It appears that some Sports Results include a "Matches" tab instead of a "Games" tab. At first glance I thought this might be for results in countries outside the US, but it appears to be determined by the type of sport.

For example, searches for Hockey, Basketball, and American Football teams all seem to return the "Games" tab.

However, searches for Soccer teams return the "Matches" tab.

We currently are not parsing any information for Sports Results with "Matches", except for the `title` and `thumbnail`. We are also incorrectly parsing the `type` into the `rankings` key.

"Matches" also seem to have a different format than games.

![Screenshot 2024-01-12 at 1 36 12 PM](https://github.com/serpapi/public-roadmap/assets/30915304/9728736b-5e5b-4ab6-8657-52d57a4b0f92)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057014?view=List) | [Inspector ( Soccer Matches 1)](https://serpapi.com/searches/65a1aab649ecdb813791f2e2/inspect) | [Inspector (Soccer Matches 2)](https://serpapi.com/searches/65a1ac982ff421c5192bcb01/inspect) | [Inspector (Basketball Games)](https://serpapi.com/searches/65a1adf04b91eb0f1a7f7ba9/inspect) | [Playground](https://serpapi.com/playground?q=atletico%2Bmadrid&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

**Comment by marm123** [comment] 2024-01-15 10:13
Duplicate of https://github.com/serpapi/public-roadmap/issues/1334

**Comment by btaunt** [comment] 2024-01-17 16:11
This should also be fixed now with the updates made for https://github.com/serpapi/public-roadmap/issues/1334

Games now parsed in original example: [Playground](https://serpapi.com/playground?q=atletico%2Bmadrid&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

**Closed by btaunt** 2024-01-17 16:11 UTC
Labels: status: queued, type: bug
