### ISSUE TITLE
[Google Search API] Support `cr` paramter

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1095] opened 2023-09-13 17:21 UTC
Google supports a `cr` parameter for limiting results to a specific country of origin. This parameter allows specifying multiple values.

A customer has requested that we support this parameter so that they can search for results from multiple specific countries at once.

<img width="1465" alt="Screenshot 2023-09-13 at 10 20 28 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5cff119b-8134-49f3-92fa-60dbd7c71104">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049298?view=List) | [Google](https://www.google.com/search?q=green+comet+nishimura&cr=countryAT%7CcountryBE%7CcountryBG%7CcountryHR%7CcountryCY%7CcountryCZ%7CcountryDK%7CcountryEE%7CcountryFI%7CcountryFR%7CcountryDE%7CcountryGR%7CcountryHU%7CcountryIE%7CcountryIT%7CcountryLV%7CcountryLT%7CcountryLU%7CcountryMT%7CcountryNL%7CcountryPL%7CcountryPT%7CcountryRO%7CcountrySK%7CcountrySI%7CcountryES%7CcountrySE&sca_esv=565038199&tbs=ctr%3AcountryAT%7CcountryBE%7CcountryBG%7CcountryHR%7CcountryCY%7CcountryCZ%7CcountryDK%7CcountryEE%7CcountryFI%7CcountryFR%7CcountryDE%7CcountryGR%7CcountryHU%7CcountryIE%7CcountryIT%7CcountryLV%7CcountryLT%7CcountryLU%7CcountryMT%7CcountryNL%7CcountryPL%7CcountryPT%7CcountryRO%7CcountrySK%7CcountrySI%7CcountryES%7CcountrySE&source=hp&ei=5OwBZdHwIr_GkPIPqfaG6As&iflsig=AO6bgOgAAAAAZQH69F-z8AI4YiLg5iYlqbywVjgX3K2p&oq=&gs_lp=Egdnd3Mtd2l6IgAqAggAMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQLhgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDMhAQABgDGI8BGOUCGOoCGIwDSL-JDVAAWABwAXgAkAEAmAEAoAEAqgEAuAEByAEAqAIK&sclient=gws-wiz#ip=1)

**Comment by marm123** [comment] 2023-09-14 05:37
Duplicate of https://github.com/serpapi/public-roadmap/issues/459

**Comment by kagermanov27** [comment] 2023-09-14 18:41
Closing this since it is https://github.com/serpapi/public-roadmap/issues/459 as @marm123 mentioned.

**Closed by kagermanov27** 2023-09-14 18:41 UTC
Labels: next
