### ISSUE TITLE
[Google Shopping API] Scrape filter type and you might like items

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#696] opened 2023-03-03 10:37 UTC
Some Google Shopping results have filter by type and you might like items

![Screen Shot 2023-03-03 at 17 35 28](https://user-images.githubusercontent.com/99160364/222698967-744690e0-c14e-474c-945c-e26e26726716.png)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Apple+iPhone+12+Pro+5G+128GB+-+Gold&location=Sydney+CBD%2C+New+South+Wales%2C+Australia&google_domain=google.com.au&gl=au&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/6401ccff3c3fb2f49bcbe8f3/inspect)

**Comment by kagermanov27** [comment] 2023-03-03 11:11
Duplicate of https://github.com/serpapi/public-roadmap/issues/26

**Closed by kagermanov27** 2023-03-03 11:11 UTC
