### ISSUE TITLE
[New API] Brave Search

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#322] opened 2022-09-09 09:01 UTC
Example URL: https://search.brave.com/search?q=minecraft&source=web

![image](https://user-images.githubusercontent.com/78694043/189313491-a6ea2d7d-8086-4f3f-8fb1-fcfdeefb163b.png)

____

### The below section is to track the demand for this website.

User request(s):
- ...

Stackoverflow questions:

- ...

Other forums/websites:

- ...

Intercom threads:
- ...

**Comment by hilmanski** [comment] 2024-11-01 22:20
Duplicate of https://github.com/serpapi/public-roadmap/issues/74

**Closed by hilmanski** 2024-11-01 22:20 UTC
Labels: status: freezer, type: feature
