### ISSUE TITLE
[Google Search API] Redirect link served in `link` for some `related_questions`

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1373] opened 2024-01-26 16:25 UTC
In related questions, the JSON URL has Google parameters 
example: https://serpapi.com/playground?q=betmgm+promo+code&location=United+States&gl=us&hl=en&device=mobile&newPara=source
- actual url in serps is "https://www.sportsbettingdime.com/sportsbooks/betmgm/offers/",
- url in json feed is "https://www.sportsbettingdime.com/sportsbooks/betmgm/offers/&sa=U&ved=2ahUKEwjh97fusfuDAxUqL0QIHZc6CB4QFnoECAEQBg&usg=AOvVaw1BFuuJ-OWPAySGXkTHCcdU"
- the additional parameters are (&sa=U&ved=2ahUKEwjh97fusfuDAxUqL0QIHZc6CB4QFnoECAEQBg&usg=AOvVaw1BFuuJ-OWPAySGXkTHCcdU)

![image](https://github.com/serpapi/public-roadmap/assets/15785331/c9501f4b-96c2-4e18-b610-6009c5f28b19)

**Comment by kagermanov27** [comment] 2024-01-26 20:23
@githubfan21 Thanks for sharing the issue with us. Unfortunately, I cannot reproduce the problem. Could you share the Inspect Link for the problematic search?

**Comment by aciddjus** [comment] 2024-09-06 11:55
Closing this as we are not able to reproduce it. Feel free to reopen if the issue occurs again. Thank you!

**Closed by aciddjus** 2024-09-06 11:55 UTC
Labels: status: queued, type: bug
