### ISSUE TITLE
[Google Knowledge Graph API] Actual image links are missing from header

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#156] opened 2022-05-27 20:45 UTC
The image contents are missing on Knowledge Graph headers extraction:

![image](https://user-images.githubusercontent.com/307597/170786980-a1bbfa01-50ef-4b9c-9bbd-818b6d61448d.png)

References:
- https://serpapi.com/playground?q=Elon+Musk&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en
- https://serpapi.com/searches/62913730ad7fa905c21164ff/inspect
- https://serpapi.com/searches/62911667969c088c391441e7/inspect
- https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/conversation/102910000025492

**Comment by aliayar** [comment] 2022-05-30 05:54
Duplicate of #155.

**Closed** 2022-05-30 05:55 UTC
Labels: status: queued
