### ISSUE TITLE
[Google Images] Images not Parsed in a Search

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1624] opened 2024-05-23 21:00 UTC
A high-volume customer shared an example of an image search where the images are present in the HTML but not parsed in the JSON.

I wasn't able to replicate it in the Playground, but they repeated the search multiple times with `no_cache=true` with the same result.

It may be worth noting that they are using `tbm=isch` rather than `engine=google_images`.

I've also noticed that when performing `tbm=isch` searches in the Playground, they seem to be redirected to `engine=google_images`. However, this customer's searches are still registering as `tbm=isch` in the inspector.

[Customer's Search 1](https://serpapi.com/searches/664f8bfc3d6919a3beb04bb0/inspect)
[Customer's Search 2](https://serpapi.com/searches/664fa9009f55b395d2dda890/inspect)
[Attempt to Replicate](https://serpapi.com/searches/664fa51460739369f6f4fac0/inspect)
[Playground](https://serpapi.com/playground?q=Pioneer+Press+logo&gl=us&hl=en&tbm=isch&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066826?view=List)

**Comment by ishiharaf** [comment] 2024-05-24 00:56
I took a look at the user's searches and it seems the ones where he wasn't getting redirected with the `tbm` parameter was done around 3 hours after I pushed changes to solve [another issue](https://github.com/serpapi/public-roadmap/issues/1620) related to the `tbm` parameter. All his failing requests however have no `engine` parameter set, and after the changes the `tbm` parameter will only redirect if `engine` is set to `google`.

The playground will just assume `engine` is `google` if there's nothing there, see the `tbm` parameter and change the engine to `google_images`. And it seems like our API was doing the same, but our documentation lists `engine` as a required parameter. The customer was relying on undocumented behavior to get redirected to `google_images` instead of setting the `engine` parameter as our documentation says (or setting the engine to `google_images` instead of relying on `tbm`).

**Comment by martin-serpapi** [comment] 2024-05-24 07:41
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066841?view=List)

**Comment by ilyazub** [comment] 2024-05-24 13:05
My mistake, I didn't check the incoming requests for this case and didn't check the documentation (https://serpapi.com/news-results) during the code review.

We will update SerpApi code to support `tbm=nws` without an engine while still making sure `tbm` won't change non-google engine (https://github.com/serpapi/public-roadmap/issues/1620), and update our documentation to require `engine=google_news` instead of `tbm=nws`.

**Comment by schaferyan** [comment] 2024-05-24 21:21
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066886?view=List)

**Comment by marm123** [comment] 2024-05-27 05:35
> and update our documentation to require `engine=google_news` instead of `tbm=nws`.

I don't think we want to do that for News Results, as `google_news` is a separate engine (https://serpapi.com/google-news-api)

**Comment by ishiharaf** [comment] 2024-05-27 05:59
> I don't think we want to do that for News Results, as `google_news` is a separate engine (https://serpapi.com/google-news-api)

For `engine=google&tbm=nws`, we're not redirecting it to `google_news` engine. We're redirecting for Google Shopping, Videos, Local, Images, and Patents. So Google News was not affected by this last change and in fact searches still work without the `engine` being set: https://serpapi.com/search.json?q=Biden&tbm=nws&location=Austin,+TX,+Texas,+United+States

It's an example in our documentation showing that searches with the `tbm` parameter work without `engine`. I couldn't find any other example of `tbm` being used this way.

**Comment by marm123** [comment] 2024-05-27 06:05
Yeah, makes sense. I was just refering to the change in the documentation. Maybe I misunderstood it, but I thought the line I quoted suggested that we should be updating the documentation to include `engine=google_news` as a required parameter, and wanted to make sure we don't update it this way.

Anyway, it's offtopic already, so let's keep it about the Google Images issue.

**Comment by ishiharaf** [comment] 2024-05-27 07:32
It's not off-topic. You're correct, I was adding to what you said. Sorry for not being very clear. We shouldn't update news to `google_news` for being a separate engine and for the reasons I added.

**Comment by ilyazub** [comment] 2024-05-28 08:40
This issue was fixed by https://github.com/serpapi/SerpApi/pull/4874.


`engine=bing` preserved.
![image](https://github.com/serpapi/public-roadmap/assets/282605/220037f5-6f7b-402a-af9e-20d58ef7d048)
(ref: https://serpapi.com/search?q=Pioneer+Press+logo&tbm=isch&engine=bing)

`engine=google_images` added.
![image](https://github.com/serpapi/public-roadmap/assets/282605/cc1225e0-0794-4cb8-9fa7-5943ea73c497)
(ref: https://serpapi.com/search?q=Pioneer+Press+logo&tbm=isch)

`engine=google` is changing to `google_images`.
![image](https://github.com/serpapi/public-roadmap/assets/282605/a02cb945-fc8c-42a3-8cb1-e0da8b00432b)
(ref: https://serpapi.com/search?q=Pioneer+Press+logo&tbm=isch&engine=google)

> I wasn't able to replicate it in the Playground, but they repeated the search multiple times with `no_cache=true` with the same result.

@schaferyan It was possible to reproduce this error using our Search API directly. Usually, our Playground fixes incorrect parameters.

**Closed by ilyazub** 2024-05-28 08:40 UTC
Labels: status: queued, status: wip, type: bug
