### ISSUE TITLE
[Google Local Services API] Empty results are not served

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1019] opened 2023-07-31 08:07 UTC
One of our customers reported that one of the queries is taking a long time and not returning results. Upon recreating the issue in the playground we can see that it is in fact not serving anything.

<img width="1470" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/5b5b3bbe-7efa-4e72-b456-08d2e4cb8ba7">

---

When we recreate the request and get the raw body:

```html
)
]
}'

[
[
"wrb.fr",
"ps3V0e",
"[[null,null,null,null,null,null,null,null,null,null,null,[[[1,\"4 stars or more\",null,\"STARS_OR_MORE_4\",\"\",[\"STARS_OR_MORE_4\"]],[2,\"Open now\",null,\"OPEN_NOW\",\"\",[\"OPEN_NOW\"]]]]],null,[null,null,null,null,[[null,null,null,null,6]],{\"21\":[[[1690790106870927,141034720,3640861400],null,null,null,null,[[0]]]]}],[[null,\"27701\",\"0x89ace46dec0e9e7f:0xeef6c9a43274dec5\",[359684750,-789271731,360519860,-788625670]]],[null,14,null,null,null,null,null,null,null,null,4]]",
null,
null,
null,
"2"
],
[
"di",
144
],
[
"af.httprm",
143,
"-8259858025863757655",
6
]
]
```

---

We are not serving some empty results. Google's Web page isn't serving any results too:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/29078050-3e6c-47b2-85e5-5bd5ffaee7d5)

---

Some of these searches are causing an infinite loop but that seems to be a separate problem:
https://github.com/serpapi/public-roadmap/issues/687#issuecomment-1657777793

---

[Inspect(Recreated without infinite loop)](https://serpapi.com/searches/64c75b634d443d9c1895ada4/inspect)
[Playground](https://serpapi.com/playground?data_cid=6745062158417646970&engine=google_local_services&hl=en&q=child_care)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000045471)

---

Jointly reported with @marm123

**Comment by dsojevic** [comment] 2024-11-22 12:17
I've been unable to reproduce this. I also ran a set of 200 searches using the parameters from the playground link above and came out with the following results, indicating it is in good health:

| Category         | Number of Requests | Average Reported Time | Average Result Count |
|------------------|--------------------|-----------------------|----------------------|
| Total          | 200                | 1.03415               | 1.94                 |
| Valid Requests   | 200                | 1.03415               | 1.94                 |
| Invalid Requests | 0                  | -                     | -                    |

There was only a handful of the searches that yielded no results, but the reported time for these was in line with the rest and it did not yield an error status.

I'm going to close this and mark it as `wontfix` for now; we can reopen this if the issue reoccurs.

**Closed by dsojevic** 2024-11-22 12:17 UTC
Labels: status: wontfix

**Comment by zyc9012** [comment] 2024-11-22 12:47
@dsojevic Let's close it with "not planned"

![image](https://github.com/user-attachments/assets/09129df6-15f8-4fe4-a470-7f1eae87060b)
