### ISSUE TITLE
[Baidu Search API] Some layout of financial_results not parsed on mobile

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#492] opened 2022-11-11 12:23 UTC
<img width="354" alt="image" src="https://user-images.githubusercontent.com/3034310/201342756-2d9bd2df-ce16-406e-b891-dfba17a24363.png">

`tpl = jr_stock_kg`: [Inspect](https://serpapi.com/searches/636e3c6e58762b1b69323fc2/inspect)

<img width="356" alt="image" src="https://user-images.githubusercontent.com/3034310/201342850-cbf566de-9e19-4c6d-89da-037897f776b0.png">

`tpl = jr_stock_index`: [Inspect](https://serpapi.com/searches/636e3e4cc573d5a0c0e78b3b/inspect)

**Comment by aciddjus** [comment] 2024-06-14 12:08
Duplicate of: https://github.com/serpapi/public-roadmap/issues/46

**Closed by aciddjus** 2024-06-14 12:08 UTC
Labels: status: freezer
