### ISSUE TITLE
[Google Finance API] Search by company name

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1870] opened 2024-08-26 05:06 UTC
A customer requested to be able to access Google Finance data based on the company name, not just the ticker name.  So far, we have suggested getting this data from Google Knowledge Graph, but it hasn't always been reliable.

When performing a search on the search box and directly hitting "return," Google Finance redirects to the available company. It would be perfect if we could do this as well.

As an alternative:
I'm thinking of adding a new API for the search results from the Google Finance search box. So, our customers can find an option to get this data.

![CleanShot 2024-08-26 at 13 02 12@2x](https://github.com/user-attachments/assets/45d72c76-7f87-4985-90f4-a24f990b1429)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069634?view=List)  
[Intercom - potentially interested in this as well](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000060362?view=List)

- [ ] Update blog post on scraping stock information once it's available.

**Comment by Rajyavardhan-Ranawat** [comment] 2024-08-26 05:19
Hi, the issue is i am not able to get the ticker code for every company in "knowledge graph" like api will provide the code for apple but not for paypal.

**Comment by aciddjus** [comment] 2024-08-26 11:58
Thank you, @hilmanski and @Rajyavardhan-Ranawat!

We could consider adding a Google Finance Autocomplete API. Similar to our [Google Trends Autocomplete API](https://serpapi.com/google-trends-autocomplete) and [Google Autocomplete API](https://serpapi.com/google-autocomplete-api).

----------

@hilmanski, Can you add a Front/Intercom link to the request?

**Comment by marm123** [comment] 2024-09-06 12:12
I opened a feature request for Google Finance Autocomplete API: https://github.com/serpapi/public-roadmap/issues/1905

@aciddjus do you think this is the most feasible or even the only solution? Asking because if so, we can close this thread in favor of https://github.com/serpapi/public-roadmap/issues/1905

**Comment by aciddjus** [comment] 2024-09-06 12:26
@marm123 We can either have a new API, as I mentioned above, or we can add a new parameter to Google Finance API as we did for the `window` parameter (new request, new layout, same engine).

<img width="338" alt="image" src="https://github.com/user-attachments/assets/a00c1ade-66b4-4726-80d2-1a76098b198e">

----------

However, in this case, it makes more sense to separate autocomplete from Google Finance API for consistency with other engines.

**Comment by marm123** [comment] 2024-09-06 12:29
Thanks @aciddjus, that makes sense. Let's close this issue in favor of https://github.com/serpapi/public-roadmap/issues/1905 then.

**Closed by marm123** 2024-09-06 12:29 UTC
Labels: status: triage, type: feature

**Comment by Rajyavardhan-Ranawat** [comment] 2024-09-13 15:29
So , at the end what should i change in my code can anybody explain.

**Comment by NateSkiles** [comment] 2024-09-13 16:51
Hi @Rajyavardhan-Ranawat, this issue was closed in favor of [[New API] Google Finance Autocomplete API #1905](https://github.com/serpapi/public-roadmap/issues/1905), so no changes are needed at this time.

The idea being we would implement a search for company names similarly to our [Google Trends Autocomplete](https://serpapi.com/google-trends-autocomplete) and [Google Autocomplete](https://serpapi.com/google-autocomplete-api) APIs.

Feel free to add any thoughts to #1905.
