### ISSUE TITLE
[Yelp] Scrape Business Profiles

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#822] opened 2023-05-02 17:52 UTC
One of our Enterprise Customers have requested that we scrape business profiles from Yelp in addition to reviews. They specifically mentioned hoping to scrape the business address from here.

<img width="654" alt="Screenshot 2023-05-02 at 10 48 32 AM" src="https://user-images.githubusercontent.com/30915304/235745247-6fb852a5-37cc-49eb-9b03-827f24027811.png">

[Yelp Business Profile](https://www.yelp.com/biz/illegal-petes-south-broadway-denver-2?osq=illegal+pete%27s) | [Intercom ](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040595?view=List)

**Comment by aciddjus** [comment] 2023-05-03 10:07
Duplicate of: https://github.com/serpapi/public-roadmap/issues/114

**Comment by schaferyan** [comment] 2024-01-04 00:52
Closing this as it has already been completed in https://github.com/serpapi/SerpApi/pull/2768

**Closed** 2024-01-04 00:52 UTC
Labels: status: wip
