### ISSUE TITLE
[Google Jobs API] Empty Responses Taking 30+ Seconds to Return

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1407] opened 2024-02-12 21:56 UTC
A customer reported Google Jobs searches with empty results are taking a long time to respond. They are aware that the searches are empty on Google's side, but the long response time slows down their process.

<img width="1166" alt="Screenshot 2024-02-12 at 1 49 31 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/76b1f56d-ad4e-4bb3-bfef-d087ea0f195f">

[Inspector](https://serpapi.com/searches/65ca6227116a55c25db669a5/inspect) | [Playground](https://serpapi.com/playground?engine=google_jobs&q=COLI+Bulk+Carriers+GmbH&location=Germany&google_domain=google.de&gl=de&hl=de) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058921?view=List)

**Comment by KotlinFactory** [comment] 2024-02-13 12:11
Didnt happen previously

**Comment by marm123** [comment] 2024-02-15 10:29
The user followed up on this, as the API is unusable for them in the current state. I'm changing it to prioritized, as Google Jobs API is one of the most used APIs we offer.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058921?view=List)

**Comment by KotlinFactory** [comment] 2024-02-19 21:58
Any update on this so far? This really is a blocker

**Comment by tanys123** [comment] 2024-02-20 06:10
@KotlinFactory Google is [rolling out a new UX for Germany](https://www.alexanderchukovski.com/new-google-jobs-ux-now-being-tested-in-germany/) and a few other countries. Requests are being redirected to the new UX, but we have to stick to the old layout for parsing to work correctly until we adapt to the new layout. We will update you once we have implemented the new layout. Thank you.

Old layout:
<img width="1450" alt="Screenshot 2024-02-20 at 2 05 37 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/fec58264-aa9f-4615-8897-2f7379e39de4">

New layout:
<img width="860" alt="Screenshot 2024-02-20 at 2 04 24 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/5af0bb12-964a-43b9-8dd9-b0c038a01de5">

**Comment by dsojevic** [comment] 2024-11-12 12:04
There was overlap with the following issue: https://github.com/serpapi/public-roadmap/issues/1798

Which was resolved with this PR: https://github.com/serpapi/SerpApi/pull/5075

I believe this has been addressed as I've been unable to reproduce the issue, so I'm going to close it out.

**Closed by dsojevic** 2024-11-12 12:04 UTC
Labels: status: prioritized, type: bug
