### ISSUE TITLE
[Google Finance API] Support `window` Parameter.

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1070] opened 2023-08-29 00:27 UTC
Google Finance includes a `window` parameter for specifying the date range. A customer has requested we add support for this parameter.

The parameter seems to correspond to the values displayed just above the graph.

<img width="1196" alt="Screenshot 2023-08-28 at 5 19 11 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/afa0be70-5f22-45a4-a3e4-db32ca565f62">

[Google](https://www.google.com/finance/quote/GOOG:NASDAQ?window=MAX) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000047909?view=List)

**Comment by marm123** [comment] 2023-08-29 07:26
Duplicate of https://github.com/serpapi/public-roadmap/issues/919

**Comment by kagermanov27** [comment] 2023-09-04 14:46
Closing this as we can continue the discussion in https://github.com/serpapi/public-roadmap/issues/919

**Closed by kagermanov27** 2023-09-04 14:46 UTC
Labels: status: queued
