### ISSUE TITLE
[Google Search API] inline_images Scraped as Header Images with only Page URL

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#129] opened 2022-04-29 09:03 UTC
Inline images in this example are scraped as knowledge_graph["header_images"]. The other problem is that **only the page URLs are parsed and returned, not image URLS**.

[The Playground](https://serpapi.com/playground?q=%E6%B0%97%E5%80%99%E5%A4%89%E5%8B%95&uule=w%2BCAIQICISVG9reW8sVG9reW8sSmFwYW4g&google_domain=google.co.jp&gl=jp&hl=ja) | [The Inspect](https://serpapi.com/searches/626b83ac8ccee05d8b632bd7/inspect)

<img width="947" alt="googlejpsearch" src="https://user-images.githubusercontent.com/64849049/165915390-83dc65e8-b243-4190-81f4-b510e1b13ed1.png">

**Comment by tanys123** [comment] 2022-07-28 08:33
<img width="1238" alt="Screenshot 2022-07-28 at 4 32 53 PM" src="https://user-images.githubusercontent.com/10222402/181460193-db271566-bb07-49d8-bc69-dc2e8e29975d.png">

Not able to reproduce and parse correctly atm.

**Comment by zyc9012** [comment] 2024-01-10 13:47
Closing as unable to reproduce.

**Closed by zyc9012** 2024-01-10 13:47 UTC
Labels: status: queued
