### ISSUE TITLE
[Google Shopping API] No results for mobile searches for some locations

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#540] opened 2022-12-09 11:24 UTC
When running the query on Google Shopping API in certain locations on mobile, the results are not extracted.

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/28161162/206691477-17bd2e76-ed2f-4ab6-8a00-8c251d921633.png">

[Playground](https://serpapi.com/playground?q=Pizza&location=Paris%2C+Paris%2C+Ile-de-France%2C+France&google_domain=google.fr&gl=fr&hl=fr&filter=0&tbm=shop&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/63931a25660dbdf9a3b1b17c/inspect) | [Google direct link](https://www.google.fr/search?q=Pizza&oq=Pizza&uule=w+CAIQICIgUGFyaXMsUGFyaXMsSWxlLWRlLUZyYW5jZSxGcmFuY2U&hl=fr&gl=fr&tbm=shop&filter=0&sourceid=chrome-mobile&ie=UTF-8)
[Playground](https://serpapi.com/playground?q=Coffee&location=Berlin%2C+Berlin%2C+Germany&google_domain=google.de&gl=de&hl=de&filter=0&tbm=shop&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/63931a9f1baebbb514ad9938/inspect) | [Google direct link](https://www.google.de/search?q=Coffee&oq=Coffee&uule=w+CAIQICIVQmVybGluLEJlcmxpbixHZXJtYW55&hl=de&gl=de&tbm=shop&filter=0&sourceid=chrome-mobile&ie=UTF-8)

**Comment by kagermanov27** [comment] 2022-12-12 17:09
Duplicate of https://github.com/serpapi/public-roadmap/issues/27

**Closed by kagermanov27** 2022-12-12 17:09 UTC
Labels: status: queued
