### ISSUE TITLE
[Google Jobs API] Slow response times and failed queries

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1798] opened 2024-07-23 18:34 UTC
A customer reached out letting us know they were receiving 503 errors from the Google Jobs API.

![image](https://github.com/user-attachments/assets/4073675b-d4f4-4482-bf1b-3ee433867f84)

![image](https://github.com/user-attachments/assets/1e304b43-c520-4869-8fa1-5a5cdafb3112)

Additionally, I'm unable to get a response in the Playground:

[https://serpapi.com/playground?engine=google_jobs&q=Barista&no_cache=true](https://serpapi.com/playground?engine=google_jobs&q=Barista&no_cache=true)

![image](https://github.com/user-attachments/assets/986ded78-8050-4f75-a456-a8dff0c3e480)

It looks like this started around 2024-07-23 11:58:10 UTC.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068887?view=List)

**Comment by schaferyan** [comment] 2024-07-23 18:47
Another user reported this:

[Front](https://app.frontapp.com/open/msg_2fmt1xp8?key=N3uqf0vDwFJzhPDjk3Ud6xzhWVSA5gWa)

**Comment by schaferyan** [comment] 2024-07-23 18:49
@NateSkiles can you add an intercom link for the customer who reported this?

**Comment by NateSkiles** [comment] 2024-07-23 19:05
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045445?view=List)

**Comment by sonika-serpapi** [comment] 2024-07-23 21:51
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/mentions/conversation/102910000068891?view=List)

**Comment by schaferyan** [comment] 2024-07-23 23:58
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068894?view=List)

**Comment by marm123** [comment] 2024-07-24 05:19
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068895?view=List)

**Comment by marm123** [comment] 2024-07-24 05:20
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068896?view=List)

**Comment by martin-serpapi** [comment] 2024-07-24 08:47
Another high-volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068919?view=List)

**Comment by martin-serpapi** [comment] 2024-07-24 11:10
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068922?view=List)

**Comment by martin-serpapi** [comment] 2024-07-24 11:12
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068923?view=List)

**Comment by martin-serpapi** [comment] 2024-07-24 11:41
Another high-volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068925?view=List)

**Comment by aciddjus** [comment] 2024-07-24 12:30
Thank you, everyone, for your patience while we work on this issue. We apologize for the inconvenience.

We have deployed a partial fix, adding support for the new Google Jobs layout, and will continue to improve our parser in the coming days.

**Comment by alexbarron** [comment] 2024-07-24 12:34
We received another report of this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068926?view=List)

It does appear success rates are increasing.

**Comment by schaferyan** [comment] 2024-07-24 15:18
Another customer report (from before the partial fix):

[Front](https://app.frontapp.com/open/msg_2fo6efrw?key=BoUDG4LSRT4fG6-CA6wR8fVHBL0i0s_w)

**Comment by Freaky** [comment] 2024-07-24 15:21
Success rates have been stable at 100% for a few hours now:

![google-jobs-error-rate](https://github.com/user-attachments/assets/7934b231-ee44-4e39-b199-aae9fa17b957)

Average response times actually look better than before:

![google-jobs-response-time](https://github.com/user-attachments/assets/d4a7db81-a14a-4ecb-a802-983c6884a7dc)

Known issues:

- No pagination support
- `related_links` are unavailable
- chips support isn't yet implemented

**Comment by schaferyan** [comment] 2024-07-24 18:58
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068933?view=List)

**Comment by NateSkiles** [comment] 2024-07-24 22:53
Another customer reported this (specifically unavailable `related_links`):

[Front](https://app.frontapp.com/open/cnv_1c18bjrw?key=zDXezli0mxnhsjpqeQXdrNnavIGjD0dk)

**Comment by martin-serpapi** [comment] 2024-07-25 07:41
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068941?view=List)

**Comment by alexbarron** [comment] 2024-07-25 08:41
Received a report specifically asking about `related_links`:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068944?view=List)

**Comment by alexbarron** [comment] 2024-07-25 11:19
Received a request specifically for pagination:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068894?view=List)

**Comment by alexbarron** [comment] 2024-07-25 15:56
Received a couple reports about `apply_link` missing in the encoded `job_id`:

[Front](https://app.frontapp.com/open/cnv_1c0jypwc?key=BoUDG4LSRT4fG6-CA6wR8fVHBL0i0s_w)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068923?view=List)

**Comment by alexbarron** [comment] 2024-07-26 15:40
This could be a separate issue, but while helping a customer, I noticed their Google Jobs query didn't return results if it was all caps. The same query in all lower case letters returned results as expected. The query in all caps worked before the Google Jobs layout change which is why I suspect this may be related.

[Playground upper case](https://serpapi.com/playground?engine=google_jobs&q=QUEREINSTEIGER&location=Leipzig%2C+Saxony%2C+Germany&google_domain=google.de&gl=de&hl=de)

![image](https://github.com/user-attachments/assets/6f252447-229a-443b-817f-a17e9eed516e)

[Playground lower case](https://serpapi.com/playground?engine=google_jobs&q=quereinsteiger&location=Leipzig%2C+Saxony%2C+Germany&google_domain=google.de&gl=de&hl=de)

![image](https://github.com/user-attachments/assets/d1da4f0d-40ff-41b5-b50e-eff397aa00dc)

For comparison, I can run the query in all caps in actual Google Jobs and get results so it does seem related to us.

[Google Jobs Query](https://www.google.com/search?q=QUEREINSTEIGER&uule=w+CAIQICIWTGVpcHppZyxTYXhvbnksR2VybWFueQ&start=0&udm=8&jbr=sep:0)

![image](https://github.com/user-attachments/assets/b13e508f-e08d-4459-ae69-4ecb9f5252b8)

[Front](https://app.frontapp.com/open/cnv_1c2dse70?key=9cXK_cWSbZmkz_Zxzl4hVXzCcOLPUj4x)

If this is a separate issue, please let me know and I'll create a new issue.

**Comment by Freaky** [comment] 2024-07-26 18:38
Thanks @alexbarron, that's an interesting example!  It can be reproduced directly on Google by [specifying `hl` and `gl`](https://www.google.com/search?q=QUEREINSTEIGER&uule=w+CAIQICIWTGVpcHppZyxTYXhvbnksR2VybWFueQ&start=0&udm=8&jbr=sep:0&hl=de&gl=de):

![empty-google-jobs-result](https://github.com/user-attachments/assets/31ce6aed-0b3a-4ab1-aad0-24f7b6b73fed)

Unsetting `gl` appears to work in this case: [Playground](https://serpapi.com/playground?engine=google_jobs&q=QUEREINSTEIGER&location=Leipzig%2C+Saxony%2C+Germany&google_domain=google.de&hl=de) (note you will need to unset the field manually as Playground JavaScript automatically resets `Localization` fields based on `Geographic Location` on load - we should perhaps revisit this behaviour)

![google-jobs-gl](https://github.com/user-attachments/assets/b2f3fb63-2d88-41ff-b190-3b288b02751d)

Another problematic case I've noticed is Ireland, where setting `gl` *or* `hl` gives empty result pages: [Playground](https://serpapi.com/playground?engine=google_jobs&q=barista&location=Ireland&google_domain=google.ie&gl=ie&hl=en).  Unsetting both is the needed workaround in this case.

I need to investigate further to see what other combinations cause problems.

**Comment by sonika-serpapi** [comment] 2024-07-26 19:01
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/mentions/conversation/102910000068989?view=List)

**Comment by martin-serpapi** [comment] 2024-07-29 06:53
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069014?view=List)

**Comment by martin-serpapi** [comment] 2024-07-29 07:56
Another customer reported this:

[Front](https://app.frontapp.com/open/cnv_1c3gdbvg?key=M6DOxrBeKSLPhIu9QfoP0h_2tkqapcag)

**Comment by Freaky** [comment] 2024-07-29 10:16
A new update to the API has been deployed.

- Pagination support has been added.  This requires client-side changes, as the numeric `start` parameter has been replaced with an opaque `next_page_token` available from `serpapi_pagination.next_page_token`. Searches with a `start` parameter will fail with an appropriate error message instead of returning empty results.
- `location` and `via` extraction has been improved and should now work across all locales and without the word `via` or its localised equivalent.
- `extensions` extraction has been improved.
- `detected_extensions` now includes additional extractions for things like `dental_coverage` and `health_insurance`.
- `job_highlights` are now extracted from JavaScript structures instead of being parsed out of description text.
- `share_link` has been added, providing a URL to link back to the job on Google.
- `apply_options` provides a list of job application links that were previously only available from the `google_jobs_listing` engine. This replaces the undocumented single link that was previously encoded in `job_id`.

Remaining work:

- `chips` support. There's a new filtering interface and the work here will likely make it into other engines as well.
- `related_links`. These require an additional subrequest for each job - they may end up in the `google_jobs_listing` engine.
- Updated documentation for the new fields.
- Prettified HTML for paginated requests. The raw pages are usable, if a bit messy.

Thanks for everyone's patience.

**Comment by stuartskelton** [comment] 2024-07-29 11:11
FYI, the playground needs updating `https://serpapi.com/playground?engine=google_jobs&q=Golang&location=London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&start=0` 

get this error 

```
{
"error":
"The `start` parameter has been removed, please use `next_page_token` for pagination."
}
```

**Comment by Freaky** [comment] 2024-07-29 12:03
Thank you @stuartskelton - seems to be an issue with how we clear our Cloudflare cache after deployment.  I manually cleared `https://serpapi.com/playground?engine=google_jobs` and now see the updated form.

I'll open an internal issue to improve this.

**Comment by sonika-serpapi** [comment] 2024-07-29 21:56
One high volume customer was not sure how to use the ```next_page_token``` parameter. 
Can we perhaps add to the documentation on the [Google Jobs API page](https://serpapi.com/google-jobs-api#api-parameters-pagination) to specify where users can get the token from to specify in the parameter?
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069047?view=List)

**Comment by SoulEvill** [comment] 2024-07-30 07:16
Thanks for updating the API.

I've just implemented the next_page_token for my application which usually pull 5 pages result. 

The data looks odd - for example, thumbnail 

after page 1 are all empty (it does have a url value but it is point to an empty gif) 

Here is screenshot on playground on page 2 where you can see thumbnail are all empty. 

![image](https://github.com/user-attachments/assets/e52fca5f-7c17-44b2-9505-db84e7f8b6d2)

**Comment by martin-serpapi** [comment] 2024-07-30 08:10
Another customer reported the issue with the thumbnails in the response when paginating. I was able to reproduce it in the Playground:

![image](https://github.com/user-attachments/assets/fe29687f-071f-4378-a7a1-dbb16fbf727d)

[Playground](https://serpapi.com/playground?engine=google_jobs&q=Barista&next_page_token=eyJmYyI6IkVyWUVDdmNEUVVwSE9VcHJUbVpNWW01WWFrWnZhMVJRZGpobk0wMHhNV2sxTFhjemQxSlFRbGxZUkhoaWIzVkJWVlozTTB3eVZDMW1TR1pGTjI5UlYwRmtYMWR4Ym5kdlVIZElkSGxpZVhSMFpXSXRYMkZ1V1hsMlR6a3RkM00yYlVsSGRIRmtURGw0YWpOZldraHJXVVZhYlRsZlRtbFdXalpNYW5BeFJERnZUVGRTTkVGWlkyTTJUVFk0UW1oNFRtMVRSREZtWDNSMU4weDFhR2hhT0ZGS1gxZHlWMms0TjNoaVEySlFOR0Z1TWpKcVJrZHZRamhFWlhCVFoySlpaalpwTUZsNUxVWmtiRlk1WHpSUVQxRjZVSGgyZVVRMGJVNUxWekl5Vld4SFVWZE5ObGhYVUhGcVQweEJPVWhKUlRWcVUwZGxhWEpFZWxwcWJXOTBNVVZEYW5SQ1lqbFZRa1ZSU0VsbmJFZ3lUVnByYms1WU1XcElWRWhhVlVWeFEySmxiVlZTVDBWV1FtaGhjbm90VVdNeGRsZHhWREpaYlRCS1ZDMXdkVWxSTkZsSVdWcHFabDlsTWxoeFowWnNkV280VXpOVWIyeEliWE0yT0ZBelpVSm9Walo2VVcwMFUwRnlabUpNVWxKbldXcHZlbEJmY1VRelJGRnZkbTVEZVdabVNtVmZaREY0U1VkcU5sVnBWRWc1YlMxM1dHTm5UVk41VmxnM2RGWnBhRmgzZDBsNWEwTkdkako1TUd0RmFuSmpaV2RYT0VGTWVXSndXVWRTUTIxS2VGZFlkREo2WW5WNVdrNTFUVVJaTlRrNVRYcGhMVTltZFcxcU5rZEJhVkpoY1ZKQmFWcGpUV3MxVEROUFUwMTZPVmd6TlZaSlppMUNjVzhTRmkxd1EyOWFkRzFuVHpWeFYydFFTVkF0YjNGalJVRWFJa0ZHV0hKRlkzRXpOMUF3U0hCUVNFbzNlWGgxY0V3MlIzUlNaRXM1WlMxWU1IYyIsImZjdiI6IjMifQ%3D%3D) | [Inspect](https://serpapi.com/searches/66a8913a3c3fb2edceb088af/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068911?view=List)

**Comment by martin-serpapi** [comment] 2024-07-30 09:19
A customer reported that there's an issue with the formatting of the results in the Playground when paginating. I was able to reproduce it:

![image](https://github.com/user-attachments/assets/5dfedfc2-789a-45f0-8d6a-fbc60bd613ef)

[Playground](https://serpapi.com/playground?engine=google_jobs&q=Barista&next_page_token=eyJmYyI6IkVzd0VDb3dFUVVwSE9VcHJUVjlmTWpCNFRqaENSVmcxVVVwVFVYWkxNR2x4UVZWTlNIbHlOV3BsYzBWS1gybGhibTR0YjNoMU5HdEpUVXRvYmw4d1NsTmZVRlV0YTJoNlRTMUdSVE0xWmpKSE1USk5NVkZGWVc0NVJFVTVaV1JJTVVndGExRmtYMTlHVG5OUlZFWTNkR05qVmtkTGRtSjBOV00yVlZSSFkycEJWbDlXVmtwaU1HZDVUMVIyVkcxU2VFcE9NRVZJTUhKM1lXZENTRGM1V1ZRMGVYcDFVRVp2ZEZOdFUwZDZkSFJ1TFcxb2JYbGxORkJNWTBKTk9HeFJZamx6ZFhSUWQzRmlPR05PUTJKVFNVaEdNMmQ1V0Uxb2NqWm5WSGxITTFabVpXaENjSGRzV0c5R1h6SlhNMDVOYkVwcVJYaEtkbU16WHpkM1puRXlYMHROVWxGWlJ6bFNkMG90T1RGdmQyNUZkMXB3WVRNeU1WWjJXVFJDTTFKNU1FcDFkWE5WTmpWdkxVaE1VVGhVVmpaQmEyaDZjbTV0T1d0cWVIUXhkRnBUTm5GT00xSk9OSE5vTFRob1JXRm5Sek5wWWtaYVRXZHBjVUZFYzI5WVZEVm5kRGhMVUZwc2FpMDNRelY1YTJwNGVWWldabk16WjFSaVFuRmlZemhJVFVacVpuVkZibTFyVm1sc2RIWldSMmMyVXpGclVXWm5kV2w1WTB4QlJWZFhabXRaUjBaUFJWVk1NemhaVkU5eVFqWm5kV1pPVmtWdlpIcG1OM0YwYWtacVZFVktkMDVSZVdwYVFXazFja05zZVVORVVYSlRSblpGVGpsdE1IbHVNbmw2Vm1OR1UwSkJkVU5rWlhsalNWZGhUa3QzTUhCNU1tVmtXVFpDTlhkRmRrcE5VMUZ6VkRNeFpERkxNRWg0YmxnU0YwMDJObTlhYjE5Q1EzVlFhelZPYjFCdVkwaGlORUZWR2lKQlJsaHlSV052VmtoVk0xYzJTblp0YVd3ellYZEJXV1Z2YTB4V2RsaEtWbWxSIiwiZmN2IjoiMyJ9) | [Inspect](https://serpapi.com/searches/66a8ae4e1e803f1415eecd81/inspect)

[Front](https://app.frontapp.com/open/cnv_1c3gdbvg?key=M6DOxrBeKSLPhIu9QfoP0h_2tkqapcag)

**Comment by Freaky** [comment] 2024-07-30 13:11
@SoulEvill @martin-serpapi  Thanks for the reports - I forgot to mention thumbnails weren't being extracted from paginated pages correctly

I've opened the following new issues to track the remaining work now that the core issues of slow response times and failed queries is resolved:

- #1809 to track prettified HTML output for paginated pages on the Playground
- #1810 to track `thumbnail` extraction on paginated pages
- #1811 to track the new search filtering interface that has replaced `chips`
- #1812 to track the missing `related_links` section
- #1813 to track the problem of empty results with some `gl` and `hl` parameters

**Comment by ArmanNisch** [comment] 2024-08-06 08:38
@Freaky Question: If the `next_page_token` token is the only way to paginate, how can we call, let's say, page **20** without having to first go through all the prior _19_ pages?

With the `start` this was obviously no issue.

**Comment by martin-serpapi** [comment] 2024-08-06 09:09
Thank you for the question @ArmanNisch . Unfortunately, there's no way to skip pages when using the `next_page_token` for pagination. Each response from the Google Jobs API contains the `next_page_token` value for the next page of results.

Please note that this is a limitation from Google, and not our API. I'm sorry for any inconvenience it may cause. If you have any follow-up questions, just let me know.

**Comment by hilmanski** [comment] 2024-08-08 00:31
A customer requested that we should still scrape the original image link. 

Sidenote, they mentioned, that the current SerpApi link didn't last very long. AFAIK, it should be last for a month.

[Front](https://app.frontapp.com/open/cnv_1ce7atuk?key=AgPXILWBdi2w3EHnhL-unhXpf6vyU6Ga)

**Comment by hilmanski** [comment] 2024-08-13 03:57
A customer complained about the update from `start` to `next_page_token`. Let's make this clear in the documentation, either informing about the update or clarifying where users can get the value from.

**Comment by aciddjus** [comment] 2024-08-14 12:01
We have added a small update to our [documentation](https://serpapi.com/google-jobs-api#api-parameters-pagination-next-page-token) regarding the `next_page_token` and `start` parameters.

<img width="829" alt="image" src="https://github.com/user-attachments/assets/f8bb391c-ee65-44a7-b810-3439986c5fca">

**Comment by marm123** [comment] 2024-12-19 06:46
It looks like the response times have stabilized over the past couple of months. I'm closing this for now. Feel free to reopen if you see this still being an issue.

**Closed by marm123** 2024-12-19 06:46 UTC
Labels: status: urgent, status: wip, type: bug
