### ISSUE TITLE
[Home Depot Search API] Returning Internal SerpApi error

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1004] opened 2023-07-21 06:18 UTC
Home Depot Search API returns Internal SerpApi error.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/c621c6b6-e262-424c-ab5c-fef09bde8e3c)

[Playground Link](https://serpapi.com/playground?engine=home_depot&q=Coffee&country=us&no_cache=true) | [Inspect Link](https://serpapi.com/searches/64ba2276c99903752c849f8d/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045003?view=List)

**Comment by schaferyan** [comment] 2023-07-21 17:48
I think this is a duplicate of #1001, it should be fixed now

**Closed by schaferyan** 2023-07-21 17:48 UTC
Labels: status: queued
