### ISSUE TITLE
[Local "Places" Results API] Not Scraping and Returning GPS Coordinates

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#484] opened 2022-11-08 14:23 UTC
[Local "Places" Results API](https://serpapi.com/local-results) is not parsing the GPS coordinates of the listing and returning 0 as the value for both latitude and longitude.

<img width="677" alt="local_results_gps" src="https://user-images.githubusercontent.com/64849049/200589031-e39f2d0e-8322-41d8-a14c-e5fbabb070ba.png">

[The Playground](https://serpapi.com/playground?q=starbucks&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=lcl&device=desktop&google_domain=google.com) | [Inspect](https://serpapi.com/searches/636a64841d64ea19e81d1b32/inspect)

**Comment by hartator** [comment] 2022-11-08 23:29
Duplicate of https://github.com/serpapi/public-roadmap/issues/479

**Closed by hartator** 2022-11-08 23:29 UTC
Labels: status: queued
