### ISSUE TITLE
[Google Search API] Some `inline_videos` blocks not parsed for some searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1032] opened 2023-08-08 12:52 UTC
<img width="1179" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/e2b3045e-d586-4f55-bd29-787ec93351cd">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=50&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client)
[Inspect](https://serpapi.com/searches/64d2276b9c84acd8395a59ea/inspect)

**Comment by aciddjus** [comment] 2024-05-30 14:02
Closing this as I can't reproduce it.

**Closed by aciddjus** 2024-05-30 14:02 UTC
Labels: status: freezer
