### ISSUE TITLE
[Google Search API] Links are not parsed correctly for some search results on mobile

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#306] opened 2022-09-05 12:02 UTC
Some search results for Google Search API on mobile return redirect link instead of the direct `link` in `organic_results`

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/28161162/188443264-be70ec2d-fc15-49d4-a6c5-72ae9abada21.png">

<a href="https://serpapi.com/searches/63141ac6d04d6d4ce02333b0/inspect">Inspect</a>

**Comment by hartator** [comment] 2022-09-06 01:43
Sometimes Google tries new layout versions in non-US languages. It's a way for them to beta test live. It's likely that they will expand that new version to all languages soon. I've switched the issue to `urgent`.

**Comment by ilyazub** [comment] 2022-09-06 09:09
This specific HTML was fetched using an outdated user agent: `Mozilla/5.0 (Linux; Android 6.0; LG-X230) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.119 Mobile Safari/537.36`.

Related to https://github.com/serpapi/public-roadmap/issues/161 and https://github.com/serpapi/public-roadmap/issues/240. Will be fixed by https://github.com/serpapi/SerpApi/pull/3108.

**Comment by schaferyan** [comment] 2023-09-13 19:27
@ilyazub I don't think we've had any new complaints about this. Is there a good way to test this, or do you think it's safe to close?

**Comment by ilyazub** [comment] 2023-09-14 17:07
@schaferyan Unfortunately, the issue is still actual. Example [Search Inspect](https://serpapi.com/searches/650338421988e52c727d3edc/inspect).

![image](https://github.com/serpapi/public-roadmap/assets/282605/f6635244-542a-4786-9f94-4b8500f76fec)

@ritu1337 The old layout was returned despite a modern user-agent.

Here's an actual Google response for that device:

![image](https://github.com/serpapi/public-roadmap/assets/282605/0a8ea4e0-26ca-4619-a4dc-8d10cd314041)

---

The `link`s starting with `https://www.google.com/url=?`were fixed in https://github.com/serpapi/SerpApi/pull/981/. The current issue is with other `google_domain`s.

**Closed** 2023-09-19 20:44 UTC
Labels: urgent
