### ISSUE TITLE
[YouTube Search API] Wrong parsing of views in "shorts_results" section

### ISSUE THREAD

**Issue by hesoia** [serpapi/public-roadmap#1861] opened 2024-08-22 16:29 UTC
When querying YouTube API in Russian language, field "views" in "shorts_results" section is not parsed correctly. For example:
```
{
    "title": "World’s Most Expensive Coffee",
    "link": "https://www.youtube.com/shorts/jGAJCAuV3pQ",
    "thumbnail": "https://i.ytimg.com/vi/jGAJCAuV3pQ/hq720.jpg",
    "views_original": "192 млн просмотров",
    "views": 192,
    "video_id": "jGAJCAuV3pQ"
}
```
`views` should be 192000000,
```
 {
    "title": "Obi-Wan Drinks His Coffee",
    "link": "https://www.youtube.com/shorts/VmQh26H0HFI",
    "thumbnail": "https://i.ytimg.com/vi/VmQh26H0HFI/oardefault.jpg",
    "views_original": "32 тыс. просмотров",
    "views": 32,
    "video_id": "VmQh26H0HFI"
}
```
`views` should be 32000
![image](https://github.com/user-attachments/assets/bbe117c0-c5b6-4939-bb1d-82691f3c6f12)
[Playground](https://serpapi.com/playground?engine=youtube&search_query=coffee&gl=ru&hl=ru)

Also, sometimes shorts are not parsed at all
![image](https://github.com/user-attachments/assets/2fb24f60-a345-4bd3-acca-693f340b1b64)

**Comment by hartator** [comment] 2024-08-22 20:23
@hesoia Thanks for reporting! 👍

We'll work on a fix for the views extraction in YouTube video shorts in Russian. 

I can't reproduce the shorts array being empty like this, but we'll issue a fix for this as well if we encounter it.

**Comment by kagermanov27** [comment] 2024-08-22 21:23
Covered in https://github.com/serpapi/SerpApi/pull/5088

**Comment by alexbarron** [comment] 2024-09-11 09:58
Another customer reported the `shorts_results` being empty:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070221?view=List)

I've been able to reproduce it consistently.

[Playground](https://serpapi.com/playground?engine=youtube&search_query=how+to+make+a+cappuccino)

![image](https://github.com/user-attachments/assets/69bb1a76-0729-43a0-8642-d4ba51c1d52d)

**Comment by hesoia** [comment] 2024-09-13 09:33
Hello again,

Are there any ETAs on fixing empty shorts section? It has happened in every request for the last 3 days now. Seems like it stopped working completely.

**Comment by NateSkiles** [comment] 2024-09-13 18:19
Hi @hesoia, unfortunately, there is no ETA for this issue at this time. However, we will be sure to provide an update here as soon as possible. Apologies for any inconvenience, and thank you for your patience while we work on a fix.

**Comment by aciddjus** [comment] 2024-10-02 12:19
@mikemorcerf Please add `status: completed` and remove other statuses only when a PR is deployed and the issue is closed. Thanks!

**Closed** 2024-10-02 14:22 UTC
Labels: status: queued, status: wip, type: bug

**Comment by mikemorcerf** [comment] 2024-10-02 15:43
Thanks for the feedback, @aciddjus. I'll do that from now on.

Thanks for opening this issue, @hesoia. The issue has been fixed and shorts_results views in Russian is now working as expected.

Here are some Playground examples:

## Thousands test
[Playground English](https://serpapi.com/playground?engine=youtube&search_query=Obi-Wan+Drinks+His+Coffee&gl=RU&hl=en&no_cache=true)
![Screenshot 2024-09-26 at 6 07 27 PM](https://github.com/user-attachments/assets/86605fa4-c316-4b01-9367-9cd0e2c4218b)


[Playground Russian](https://serpapi.com/playground?engine=youtube&search_query=Obi-Wan+Drinks+His+Coffee&gl=RU&hl=ru&no_cache=true)
![Screenshot 2024-09-26 at 5 57 24 PM](https://github.com/user-attachments/assets/5d23d46f-c385-40b5-9c3f-851a4495ad43)


## Millions test
[Playground English](https://serpapi.com/playground?engine=youtube&search_query=World%E2%80%99s+Most+Expensive+Coffee&gl=RU&hl=en&no_cache=true)
![Screenshot 2024-09-26 at 6 11 36 PM](https://github.com/user-attachments/assets/e728fffc-209e-45a7-b534-0abc71595f43)


[Playground Russian](https://serpapi.com/playground?engine=youtube&search_query=World%E2%80%99s+Most+Expensive+Coffee&gl=RU&hl=ru&no_cache=true)
![Screenshot 2024-09-26 at 5 53 36 PM](https://github.com/user-attachments/assets/657f9101-796f-49e5-b77a-ed7990213751)

## Billions test
[Playground English](https://serpapi.com/playground?engine=youtube&search_query=Real+life+transforming+Cinderella+dress&gl=RU&hl=en&no_cache=true)
![Screenshot 2024-09-26 at 6 01 26 PM](https://github.com/user-attachments/assets/9223795a-efb4-4b44-b58d-333d16dcbc6b)


[Playground Russian](https://serpapi.com/playground?engine=youtube&search_query=Real+life+transforming+Cinderella+dress&gl=RU&hl=ru&no_cache=true)
![Screenshot 2024-09-26 at 6 02 43 PM](https://github.com/user-attachments/assets/752b6c58-5af5-460e-b970-9d7958ee4640)
