### ISSUE TITLE
[Google Search API] Missing `title` in about this result in organic result

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#816] opened 2023-04-27 09:04 UTC
<img width="1357" alt="Screenshot 2023-04-27 at 4 59 56 PM" src="https://user-images.githubusercontent.com/10222402/234813645-38881d37-c0ea-4c68-b346-9b61a7f2ca55.png">

In about result we have icon, link, etc but `Site Title` is missing. It might not need be in `about_this_result` but we should parse it. This should also apply to `ads` results.

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/644a395f49ecdbc6cefb3bdc/inspect)

**Comment by aciddjus** [comment] 2023-04-27 09:29
Duplicate of: https://github.com/serpapi/public-roadmap/issues/803

**Closed by aciddjus** 2023-04-27 09:29 UTC
Labels: status: queued
