### ISSUE TITLE
[Google Search API] Results not Scraped

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#863] opened 2023-05-18 13:37 UTC
In this search example, the results are not parsed and returned although there are organic_results returned by Google.

![advanced_search](https://github.com/serpapi/public-roadmap/assets/64849049/43b5c3b6-b8b2-4ed2-9137-edd7c1fc265c)

[Inspect Link](https://serpapi.com/searches/6466199aeb31eb63a9de7455/inspect) This example show bug | [Playground Link](https://serpapi.com/playground?q=site%3Apt.linkedin.com%2Fin+(Node.js+developer)+(inanchor%3ALisbon)+(Developer)&gl=us&hl=en&start=70&num=10) This example works fine, no issues | [Google Link](https://www.google.com/search?q=site:pt.linkedin.com/in+(Node.js+developer)+(inanchor:Lisbon)+(Developer)&start=70)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041387?view=List)

**Comment by ilyazub** [comment] 2023-05-19 08:10
Looks like a duplicate of https://github.com/serpapi/public-roadmap/issues/866.

**Comment by ilyazub** [comment] 2023-05-19 09:44
Related to https://github.com/serpapi/SerpApi/pull/1945. User agents for this proxy provider result into an old HTML layout we don't support.

**Comment by marm123** [comment] 2023-05-22 07:56
I'm opening this thread as the issue persists:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041387) | [Inspect](https://serpapi.com/searches/6468a221d04d6d8b682af40e/inspect)

**Closed** 2023-05-22 14:58 UTC
Labels: urgent
