### ISSUE TITLE
[Google play product API] Add review ID on the reviews response

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1566] opened 2024-04-24 06:44 UTC
A user was looking for a review ID (a unique ID) on our response for app reviews Google Play Store. Let's see if it's possible to add this data to our response.

I believe it's available on the `data-review-id`:
![CleanShot 2024-04-24 at 14 44 09](https://github.com/serpapi/public-roadmap/assets/4522467/e8124d9c-12cb-4319-9e2e-a5ea93cbf6fc)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064206?view=List) | [Documentation](https://serpapi.com/google-play-product-reviews)

**Comment by ishiharaf** [comment] 2024-04-26 14:14
@hilmanski This is a duplicate of https://github.com/serpapi/public-roadmap/issues/830. Reviews are kinda broken (see https://github.com/serpapi/public-roadmap/issues/718), so I'm not sure what'll get done first 🤔

**Closed** 2024-04-29 14:49 UTC
Labels: status: triage, type: feature
