### ISSUE TITLE
[Google Trends API][Documentation] Add a documentation example for explaining tz parameter

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#300] opened 2022-08-31 08:56 UTC
Below are examples of both Google Trends API results and Google Trends search results with the same parameters using the same timezone:

Google Trends API results:
![image](https://user-images.githubusercontent.com/28161162/187639333-65453e03-d396-4f99-b8b1-be17aa514998.png)

Google Trends search results:
![image](https://user-images.githubusercontent.com/28161162/187639380-2139d2a7-a3ee-435b-a598-9ff5473455d0.png)

<a href="https://serpapi.com/playground?engine=google_trends&q=AMO+Price&geo=SG&tz=-420&cat=29&date=today+1-m&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/630f1ebe66d81f2cf44b078d/inspect">Inspect</a>

**Comment by tanys123** [comment] 2022-09-05 10:46
Link: https://trends.google.com/trends/explore?cat=29&date=today%201-m&q=amo

Search from US via VPN:
<img width="1212" alt="Screenshot 2022-09-05 at 6 37 10 PM" src="https://user-images.githubusercontent.com/10222402/188430266-0f22835b-999d-4675-ae16-598ca4d067d9.png">

Search from Malaysia:
<img width="1173" alt="Screenshot 2022-09-05 at 6 37 20 PM" src="https://user-images.githubusercontent.com/10222402/188430368-32461ea9-8430-48aa-a63c-324ba21d219e.png">

Google Trends show results different depend which location you are in. Not sure the reason behind it, might be that Google Trends using [random sampling data](https://medium.com/google-news-lab/what-is-google-trends-data-and-what-does-it-mean-b48f07342ee8) and the nature of distributed system that handle request on the respective region.

**Comment by marm123** [comment] 2022-09-06 06:36
Thank you @tanys123 !
The initial searches above (using our API and regular Google Trends search) were both conducted using Los Angeles as a search location (using the `tz` parameter for the Los Angeles time zone in case of our API and using VPN for regular Google Trends) so in theory, they should both return the same results.

I am probably missing something else here though.

**Comment by tanys123** [comment] 2022-09-06 06:47
@marm123 our API go through a proxy to make the final contact with Google and it is random every time. Even with same parameters including `tz` Google will still give different results.

**Comment by marm123** [comment] 2022-09-06 10:40
Got it @tanys123 ! Thanks a lot for looking into it.

**Comment by aliayar** [comment] 2022-10-28 10:37
So, is there no way to get a reliable way to get the Trends API results according to the regions @tanys123?

**Comment by tanys123** [comment] 2022-11-03 05:53
I think we can do that if our proxy region can be fixed. Currently it is randomized to avoid getting blocked. It is a structural change.

**Comment by ilyazub** [comment] 2022-11-14 16:58
Probably can use [`Proxy::Picker#pick_geo`](https://github.com/serpapi/SerpApi/blob/0456be11d52ba396353ca0748256efa5d2e014bc/app/lib/proxy/picker.rb#L44-L49) like for the Google Maps: https://github.com/serpapi/SerpApi/blob/afa1861164cf422a4c8cd444655238763c5c5153/app/lib/search_splitter.rb#L156-L157

@marm123 wdyt?

**Comment by kagermanov27** [comment] 2022-11-29 11:10
@marm123 and I investigated how`tz` works and why we have it as `420` for default.

Here are the points:

TZ is calculated by time difference to `UTC+0` multiplied by `60`. So the formula should be:

`((UTC+0 Time) - (Desired time in desired location)) * 60`

---
An Example:
Let's say the time is `2.59 AM` on `Los Angeles` that is using `PT`. Because `PT` is now currently `UTC-8` (`PST`), UTC is ahead of our desired time from `8 hours`.

This means that the `8*60 = 480` will give us the `tz` we must use in 29th of `December 2022 in Los Angeles`

In the same way, if a time zone is ahead of UTC, the `tz` will be negative since the `reference point is UTC`

---

Second Example

Los Angeles also has a second time throughout the year that is `PDT`, and that is `-7`

In that case the `tz` parameter we must use when Los Angeles is using `PDT` is `7*60 = 420`

---

Both PDT and PST are represented by PT. And the default value changes itself over time. Here is the definition of the parameter we use in our documentation:

`Parameter is used to define a time zone. The default value is set to 420 (Pacific time zone: -07:00). Value is shown in minutes and can span from -1439 to 1439. tz parameter affects timestamps in response.`

When I compare the results from Google Trends to our Google Trends API using a proxy on Los Angeles, I can spot a one hour difference. This is because by the time we implemented this part, the time zone was `UTC-7` and it was `PDT`. Now, the time zone is `PST`, and the default value changed itself.

I hope our investigation broght some light to the issue. I am opening a PR to correct the documentation, and change default value automatically from `420` to `480`

**Comment by schaferyan** [comment] 2023-05-03 22:17
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040669?view=List)

**Comment by marm123** [comment] 2023-05-05 08:07
Same issue for another user:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040723?view=List)

**Comment by hilmanski** [comment] 2023-11-17 03:19
Another user reported this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053858?view=List)

**Comment by hartator** [comment] 2023-11-22 16:17
@kagermanov27 Do you want to publish https://github.com/serpapi/public-roadmap/issues/300#issuecomment-1330462623 as part of our documentation or should we close this as a `wontfix`?

**Comment by kagermanov27** [comment] 2023-11-22 16:24
@hartator, I am assigning this to myself, and will add a small part to our documentation on what to take into consideration when setting timezones. It is worth noting that as long as https://github.com/serpapi/public-roadmap/issues/887 fluctuates between giving correct and incorrect results, this explanation will add minimal value to reducing confusion. I still see value in adding https://github.com/serpapi/public-roadmap/issues/300#issuecomment-1330462623 as a part of the documentation though.

**Comment by kagermanov27** [comment] 2023-11-29 22:36
This issue was for investigating the inconsistencies of https://github.com/serpapi/public-roadmap/issues/887 and the ambiguity on `tz` parameter.

We have separated the `tz` definition issue to https://github.com/serpapi/public-roadmap/issues/519 and resolved it with https://github.com/serpapi/SerpApi/pull/3400

Since then, we have kept this issue for backend-related issues with the Google Trends API. But then we opened https://github.com/serpapi/public-roadmap/issues/887 and carried on the conversation there.

I am renaming this issue to `[Google Trends API][Documentation] Add a documentation example for explaining tz parameter` to move all the conversation about inconsistencies to https://github.com/serpapi/public-roadmap/issues/887

@schaferyan, @marm123, @hilmanski You may direct customers if they have a problem understanding the `tz` parameter to the documentation example in https://github.com/serpapi/SerpApi/pull/4331

The main issue is not about the `tz` parameter. So, from now on, if the issue is about inconsistencies, https://github.com/serpapi/public-roadmap/issues/887 is the safe bet to report it.

**Closed** 2023-12-15 15:32 UTC
Labels: status: queued
