### ISSUE TITLE
[Google Search API] `total_results` missing in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1313] opened 2023-12-27 15:30 UTC
A customer reported that `total_results` is missing in the response from the Google Search API.

I was not able to reproduce it in the Playground, as `total_results` was always present in the response when executing requests with the same parameters as the customer.

[Customer Request Inspector](https://serpapi.com/searches/658c3a007bea275153921ce7/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055930?view=List)

**Comment by Alaa-abdulridha** [comment] 2024-01-02 19:22
@martin-serpapi

Could you please try to reproduce it? I've tried many times and tried to investigate the inspection you shared but no luck.


I think it's something related to the proxy, the connection was cut or lost during the loading of the page, since I can see that the HTML in the inspect is not complete.

**Comment by hartator** [comment] 2024-01-02 23:26
`total_results` is missing from actual Google results. It's not something we are going to be able to fix.

**Comment by marm123** [comment] 2024-01-24 11:42
I'm following up on this as another customer reported the issue. It seems that the `total_results` are sometimes returned and sometimes not for the exact same query. Is this Google's behavior? Here are examples:

No `total_results`:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ec7a8822-6c23-4c91-bafb-e6031c8422a4">

The same query was performed within one minute of the one above with the same parameters:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/7358a2e8-f360-4cb7-acb1-4b1d57fd96a5">

I want to make sure the issue is on Google's side, as I was constantly getting results with and without `total_results` via our API, but I wasn't able to reproduce it via regular Google search, as every time I tried to search something, the `total_results` were returned at the top of the SERP.

[Playground](https://serpapi.com/playground?q=site%3Ainsurgenciaautista.com.ar&location=Community+of+Madrid%2C+Spain&google_domain=google.es&gl=es&hl=es&no_cache=true) | [Inspect - no `total_results`](https://serpapi.com/searches/65b0f483224db1168956f1db/inspect) | [Inspect - `total_results` scraped](https://serpapi.com/searches/65b0f4ceeb31ebcfe0426394/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057660?view=List)

**Comment by hilmanski** [comment] 2024-01-24 23:09
A user reports a similar case.

As an alternative, we can get the total_results by visiting the last page as discussed here:
https://github.com/serpapi/public-roadmap/issues/1196
https://github.com/serpapi/public-roadmap/issues/1316

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000057716?view=List).

**Comment by marm123** [comment] 2024-04-19 13:02
Following up on this as one of our Enterprise Customers is concerned about the fact that there are no `total_results` in some requests. Can we double-check if this is an issue on Google's side, given my previous message? I couldn't get a response directly from Google with no information about `total_results` after many retries. It could be just a coincidence, but I want to make sure of that.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063931?view=List)

**Comment by marm123** [comment] 2024-04-19 13:23
Marking it as prioritized since it's a request from our Enterprise Customer.

**Comment by marm123** [comment] 2024-04-23 10:51
Another customer inquired about it.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064147?view=List)

**Comment by zyc9012** [comment] 2024-04-30 08:01
The presence of `total_results` can be affected by the cookie `NID`, for example

Cookie not returning `total_results`:
`NID=513=ngXabEqZigEOeEV8QO2a260GHF5bUIVYrViKD7Lq6Jtmi8bkjWOCyr6kt2s_aYWg-yfFjn1n4w_UpkM8DY_k6Mp-_eG9_UeGMi9sILxc0qQaUypMHqWKetGfcn5wtJcStcfYSMHZR3nO8Z5IHf8srs1FCiG5ofcWGphLQQfwq-7KxDEOga7bx79Wgdm7sjUu5Vl8a5lM84c0LrciZ3-6ib_MaN-6dmfVE8Vw1ZygFcO-FJ4LM0tlph2g`

Cookie returning `total_results`: `NID=513=VYWyUMudUUy943Z627NZrW42IGxv7FrkuTzpo5J7i041W14vu7MpRXOFs8muiN1SEsm0zhYwoAxhXxYSIgMwvEq22iXOBweM-6hGlV0XW-jorLfYWsgByA-1eq94fe11SDhpZSb0mKEmyMLN7u0c8Mk9Y1pEZlssg6J1Z6rTNgE`

**Comment by marm123** [comment] 2024-04-30 08:26
Thank you, @zyc9012, for investigating that! I'll let the customer know and close the issue now, as we don't want to force specific cookies just to get `total_results`, as there might be some side effects on the API.

**Closed by marm123** 2024-04-30 08:26 UTC
Labels: status: wontfix, type: bug
