### ISSUE TITLE
[Google Shopping Product API] Scrape "Typical Prices Across the Web" Section

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#248] opened 2022-08-03 08:20 UTC
Google has added a new element to the Google Shopping Product Results Page called "Typical Prices Across the Web".

[The Playground](https://serpapi.com/playground?engine=google_product&product_id=6203781335732593320&location=Canada&google_domain=google.ca&gl=ca&hl=en) | [The Inspect](https://serpapi.com/searches/62ea2eaf0574f56ceeacc046/inspect)

<img width="567" alt="typical_prices" src="https://user-images.githubusercontent.com/64849049/182560074-e8b8b5d1-cf5f-47c6-ad29-99e75b50e5c3.png">

**Comment by chetansatasiya** [comment] 2022-08-03 08:26
@aliayar Thanks for considering the request. Do you guys have any ETA for this?

**Comment by aliayar** [comment] 2022-08-03 13:10
As I have said before, we don't have any ETA for it but I can say that it will probably be completed in the next 4-6 weeks after the team's decision.

**Comment by kagermanov27** [comment] 2022-08-08 13:37
>  Thanks for considering the request. Do you guys have any ETA for this?

@chetansatasiya I have pushed a fix for this. After it is reviewed and approved, it will be integrated. I don't expect it to take more than a week.

**Closed** 2022-08-15 06:45 UTC
Labels: next, wip

**Comment by dimitryzub** [comment] 2022-08-15 11:03
@chetansatasiya For the sake of clarity, the issue is fixed now:

![image](https://user-images.githubusercontent.com/78694043/184624069-db836c6e-d4d2-4204-8913-a54031ffef83.png)

Test yourself: https://serpapi.com/playground?engine=google_product&product_id=6203781335732593320&location=Canada&google_domain=google.ca&gl=ca&hl=en
