### ISSUE TITLE
[YouTube Search API] Cookie pop up appears when `gl=US`, `sp` filter is present and `search_query` is empty

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#293] opened 2022-08-30 09:20 UTC
Possibly somehow relates to #261.

![image](https://user-images.githubusercontent.com/78694043/187398742-8209745c-f813-4008-917b-1b8bce46c0ff.png)

[Playground](https://serpapi.com/playground?engine=youtube&gl=us&sp=EgJAAQ%25253D%25253D) | [Inspect](https://serpapi.com/searches/630dd4e33bea7b6a7367037f/inspect)

In the playground link, the `gl` parameter maybe resets to default (empty) and will need to be added manually. Inspect link doesn't have that behavior. Hard to reproduce.

**Comment by ilyazub** [comment] 2022-10-13 07:11
Duplicate of https://github.com/serpapi/public-roadmap/issues/285?

**Comment by dimitryzub** [comment] 2022-10-13 09:40
@ilyazub Not quite sure. In the #285 `search_query` is used but in this (#293) only `sp` and `gl` parameters are used. 

I've checked and cookie pop-ups don't show up in both issues.  Should we close both issues then? WDYT?

**Comment by kagermanov27** [comment] 2022-10-19 15:30
Duplicate of #285

**Comment by kagermanov27** [comment] 2022-10-19 15:30
Duplicate of https://github.com/serpapi/public-roadmap/issues/285

**Closed by kagermanov27** 2022-10-19 15:30 UTC
Labels: status: freezer
