### ISSUE TITLE
[Google Scholar Author API] Extraction of articles in reverse order

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#52] opened 2022-03-10 12:53 UTC
Old Canny Conversation
>Dmitry: In the Playground, everything seems to be correct but in the Python package when parsing with and without pagination, articles are parsed in the wrong order (more one the screenshots).
For example, the first article appears last or the last article appears first when parsing.
I'm using the latest version (2.4.1) and not using anything related to sorting. 
A guess: this behavior might be caused by [recent articles pagination bug fix](https://forum.serpapi.com/bugs/p/google-scholar-author-api-pagination-next-token-exists-when-no-author-articles-l).  
Another guess was in the if
 statement: if "next" in results.get("serpapi_pagination", [])
 was somehow messing up the behavior, but even without pagination as said above, the article's order was out of order.
![image](https://user-images.githubusercontent.com/73674035/157665973-482193e2-ac4b-4ba0-84dd-1dfadabab9cb.png)
![image](https://user-images.githubusercontent.com/73674035/157666012-ed7d6d01-c142-4495-b709-4660055a4c15.png)
![image](https://user-images.githubusercontent.com/73674035/157666035-9227a4e9-3705-481b-ae73-e3e23b80d65c.png)
![image](https://user-images.githubusercontent.com/73674035/157666073-97c9602c-759f-4d02-a554-c1fe0b6b4a2f.png)

 >>Ali: Hello Dmitriy,
Thank you for the report. I have informed package maintainer about this.
----
[Old Canny Link](https://forum.serpapi.com/bugs/p/google-scholar-author-articles-api-extracting-articles-in-reverse-order)

**Comment by dimitryzub** [comment] 2022-10-14 06:24
Seems like there's no longer such an issue. I think we can close this one.

@kagermanov27 WDYT?

**Comment by dimitryzub** [comment] 2022-11-09 11:45
Closing per above. Feel free to open/comment if the issue is still present.

**Closed by dimitryzub** 2022-11-09 11:45 UTC
