### ISSUE TITLE
[Google Trends API] Some searches have no data

### ISSUE THREAD

**Issue by cannertang** [serpapi/public-roadmap#790] opened 2023-04-14 03:25 UTC
key word:
彈珠

Search ID: 
6438c4035119a6ef2e8315bc

The same conditions, google trends official website search has information.
https://trends.google.com.tw/trends/explore?date=today%201-m&geo=TW&q=%E5%BD%88%E7%8F%A0

**Comment by dimitryzub** [comment] 2023-04-14 04:28
Related:
- https://github.com/serpapi/public-roadmap/issues/556

Possibly related:
- https://github.com/serpapi/public-roadmap/issues/561

**Comment by ilyazub** [comment] 2023-04-14 12:57
Duplicate of https://github.com/serpapi/public-roadmap/issues/556.

**Closed by ilyazub** 2023-04-14 12:57 UTC
