### ISSUE TITLE
[Yandex Images API] HTML does not work

### ISSUE THREAD

**Issue by Alaa-abdulridha** [serpapi/public-roadmap#7] opened 2022-02-22 19:43 UTC
The HTML in the Yandex Images engine doesn't work  
  
https://serpapi.com/playground?engine=yandex_images&text=spider+man&no_cache=true  
 

![](https://user-images.githubusercontent.com/53356539/155206812-221de57a-a261-4cee-a2fd-6282ee46924c.png)

[Inspect](https://serpapi.com/searches/62153c49af5af1d67055ab63/inspect)

**Comment by aciddjus** [comment] 2022-02-23 11:45
Couldn't reproduce the issue. The screenshot below is from inspect link.

![image](https://user-images.githubusercontent.com/6929257/155312980-3cca60cf-924a-4f80-a76e-466b72b32418.png)

**Comment by Alaa-abdulridha** [comment] 2022-02-23 15:52
> Couldn't reproduce the issue. The screenshot below is from inspect link.
> 
> ![image](https://user-images.githubusercontent.com/6929257/155312980-3cca60cf-924a-4f80-a76e-466b72b32418.png)

even when I oped a thumbnail it gives me SSL error
![image](https://user-images.githubusercontent.com/53356539/155355509-da280ddc-7ebd-4f87-876e-96cd3011d2a4.png)


![image](https://user-images.githubusercontent.com/53356539/155355592-6f430b96-d014-4a50-82bd-967aa16297e9.png)


I have tried in two different devices and same issue, maybe it's blocked or something, are we using any proxies with Yandex images API?

**Comment by aciddjus** [comment] 2022-02-24 12:28
> I have tried in two different devices and same issue, maybe it's blocked or something, are we using any proxies with Yandex images API?

Got it. We don't use any specific proxies here. So it might be the case of HTML being blocked.

**Comment by aciddjus** [comment] 2024-06-14 11:00
Update: Images are not loading in HTML

<img width="2560" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/a9c7774e-9cff-40b4-b4ea-29faf5cfd932">

**Comment by Krugloff** [comment] 2024-10-08 10:49
It worked for me. Do you have a link to the fresh inspect? Did you see the images in my link?

[Inspect](https://serpapi.com/searches/67050d125ddfbad46739b3d4/inspect)

<img width="1456" alt="image" src="https://github.com/user-attachments/assets/d70d6bf7-b177-4082-92b1-95df02d463b9">

**Comment by aciddjus** [comment] 2024-10-21 11:27
@Krugloff It's working right now. Let's close this issue and re-open it as needed.

**Closed by aciddjus** 2024-10-21 11:27 UTC
Labels: status: queued, type: bug
