### ISSUE TITLE
[Google Search API] Duplicate Answer_box 

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2017] opened 2024-10-10 15:55 UTC
Hi,

When we do a search with qdr:m, if there is a anwser_box the result for the answer_box is also on top 1 organic result (there is a duplicate, see screenshot below).

![image](https://github.com/user-attachments/assets/220e11f6-3c8b-4be1-accf-82e8af1cd842)

https://serpapi.com/playground?device=desktop&engine=google&gl=fr&google_domain=google.fr&hl=fr&location=France&q=golfeur+fran%C3%A7ais&tbs=qdr%3Am

Is it possible to solve this issue.

regards

**Comment by schaferyan** [comment] 2024-10-10 16:59
Thanks for the issue, @RedBillyOne! We'll be sure to look into this and implement a fix.

**Comment by NateSkiles** [comment] 2024-10-10 17:09
Organic Result Answer Box type 1 ([docs](https://serpapi.com/direct-answer-box-api#api-examples-organic-result-answer-box-type-1)) is including the `answer_box` result in the `organic_results` array.

**Comment by schaferyan** [comment] 2024-10-10 18:48
@NateSkiles you're right, I believe this is the expected behavior as this type of answer box is also an organic result.

@RedBillyOne can you clarify if this causes any specific problems for your use case?

Closing this as unplanned for now, since this seems to be the expected behavior.

**Closed by schaferyan** 2024-10-10 18:48 UTC
Labels: status: queued, type: bug

**Comment by marm123** [comment] 2024-10-10 19:12
> Organic Result Answer Box type 1 ([docs](https://serpapi.com/direct-answer-box-api#api-examples-organic-result-answer-box-type-1)) is including the answer_box result in the organic_results array.

Actually, [specifically for this example](https://serpapi.com/playground?q=What+is+banana+(fruit)+known+for%3F&gl=us&hl=en&highlight=answer_box&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz), the first of the `organic_results` is not the same as the `answer_box`, so the behavior is different than with an example @RedBillyOne  shared.

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/197b7566-bce0-49f8-be29-e91ca3b99779">

I'm not sure which behavior is expected, but there is definitely inconsistency. We should either always include this kind of `answer_box` response as the first `organic_result` or never.

I would guess that this is a valid issue because when the `answer_box` is also the first `organic_result`, we are duplicating the entry in two separate blocks. I might be wrong, though.

**Comment by RedBillyOne** [comment] 2024-10-10 19:14
Hi,

I'm not agree, it's an issue. The aim is to have in SERPAPI JSON the same result that there is in the SERP. 

You can said that the answer_box result (type:organic-result) is in top 1 (it's fine) but in this case you can't show also in top 1 position organic result the same result (meaning website) because this meaning that the website ouest-france.fr (in the previous example)  is display in 2 position in the SERP and it's wrong. it's one or the other.

If answer_box organic_results is display, so the top 1 organic result is position :2.

Is it also logical for you ? 

Regards

**Comment by marm123** [comment] 2024-10-10 19:22
I tested a couple of different `type: organic_results` `answer_box` searches, and in all of them the first `organic_result` is different than the `answer_box` ([ref](https://serpapi.com/playground?q=Is+coffee+healty&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz), [ref](https://serpapi.com/playground?q=Who+won+2020+election+in+US&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz), [ref](https://serpapi.com/playground?q=Is+Norway+a+part+of+the+EU&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz), [ref](https://serpapi.com/playground?q=How+many+calories+are+in+Apple&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz), [ref](https://serpapi.com/playground?q=When+was+Apple+founded&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz)).

I'm reopening this as a valid issue.

**Comment by NateSkiles** [comment] 2024-12-02 22:36
Hi @RedBillyOne, I just wanted to follow up here and let you know this issue has been resolved.

Please let us know if you continue to experience this issue!

**Comment by RedBillyOne** [comment] 2024-12-02 22:41
Hi,
Yes, i confirm. It's fine.
Thank you
