### ISSUE TITLE
[Baidu Search API] Support `financial_results` on desktop

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#524] opened 2022-12-01 08:58 UTC
<img width="586" alt="image" src="https://user-images.githubusercontent.com/3034310/205009589-d9afb717-89cc-47bb-bdc4-ba138ed3f40e.png">

[Inspect](https://serpapi.com/searches/638869393e86acfa7db2fd97/inspect)

**Comment by aciddjus** [comment] 2024-06-14 12:17
Duplicate of: https://github.com/serpapi/public-roadmap/issues/46

**Closed** 2024-06-14 12:17 UTC
Labels: status: freezer
