### ISSUE TITLE
[Home Depot Product API] Returning Uncaught Null Error

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1005] opened 2023-07-21 06:21 UTC
Home Depot Product API returns Uncaught Null Error and not working.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/ed2a3352-cc86-4d07-a77e-7f35117c5fe6)

[Playground Link](https://serpapi.com/playground?engine=home_depot_product&product_id=202054749) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045003?view=List)

**Comment by schaferyan** [comment] 2023-07-21 17:51
Probably a duplicate of #1001 and should be fixed now

**Closed by schaferyan** 2023-07-21 17:51 UTC
Labels: status: queued
